name: "build"

on:
  pull_request:
    branches:
      - "master"
  # schedule:
  #   - cron: "0 0 * * */1"

jobs:
  run:
    name: "Build"
    runs-on: ubuntu-latest
    container: python:3.12-alpine

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        id: checkout
        uses: "actions/checkout@v4"
        with:
          repository: ${{ github.repository }}
      - name: "Run"
        env:
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
        run: |
          echo '${{ secrets.GOOGLE_CLOUD_SVC_CREDS }}' >> credentials.json
          pip install -r requirements.txt
          python crawl.py halloween
