name: "build"

on:
  pull_request:
    branches:
      - "master"
  schedule:
    # Run every Sunday at midnight (00:00)
    # https://crontab.guru/#0_0_*_*_0
    - cron: "0 0 * * 0"

jobs:
  halloween:
    name: "Crawl Halloween Movies"
    runs-on: ubuntu-latest
    container: python:3.12-alpine

    env:
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_HALLOWEEN_ID }}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        id: checkout
        uses: "actions/checkout@v4"
        with:
          repository: ${{ github.repository }}
      - name: "Install Dependencies"
        run: pip install -r requirements.txt
      - name: "Generate Credentials JSON File"
        run: echo '${{ secrets.GOOGLE_CLOUD_SVC_CREDS }}' >> credentials.json
      - name: "Run"
        run: python crawl.py halloween
  christmas:
    # Disable job
    if: false
    name: "Crawl Christmas Movies"
    runs-on: ubuntu-latest
    container: python:3.12-alpine

    env:
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_CHRISTMAS_ID }}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        id: checkout
        uses: "actions/checkout@v4"
        with:
          repository: ${{ github.repository }}
      - name: "Run"
        run: |
          echo '${{ secrets.GOOGLE_CLOUD_SVC_CREDS }}' >> credentials.json
          pip install -r requirements.txt
          python crawl.py christmas
