name: Bump version workflow

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: current_version
        run: echo "current_version=$(grep '# version' version | cut -d ' ' -f3)" >> $GITHUB_ENV
      - name: FragileTech/bump-version
        uses: FragileTech/bump-version@main
        with:
          current_version: "${{ env.current_version }}"
          files: version
          commit_name: Your Company Bot
          commit_email: bot@your-company.com
          login: your-bot-login
          token: "${{ secrets.BOT_TOKEN }}"
