name: "run"

on:
  pull_request:
    branches:
      - "master"
  # schedule:
  #   - cron: "0 0 * * */1"

jobs:
  run:
    name: "Run program"
    runs-on: ubuntu-latest
    container: python:3.12-alpine

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          repository: ${{ github.repository }}
      - name: "Build"
        env:
          GOOGLE_CALENDAR_API_SVC_CREDS: ${{ secrets.GOOGLE_CALENDAR_API_SVC_CREDS }}
          GOOGLE_CALENDAR_API_TOKEN: ${{ secrets.GOOGLE_CALENDAR_API_TOKEN }}
          GOOGLE_CALENDAR_API_CREDENTIALS: ${{ secrets.GOOGLE_CALENDAR_API_CREDENTIALS }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          pip install -r requirements.txt
          echo "$GOOGLE_CALENDAR_API_SVC_CREDS"
          echo "$GOOGLE_CALENDAR_API_TOKEN"
          echo "$GOOGLE_CALENDAR_API_CREDENTIALS"
          echo "$GOOGLE_CALENDAR_API_SVC_CREDS" >> svc-crawliday.json
          ls -la
          cat svc-crawliday.json
          python crawl.py halloween
