name: "unittest"

on:
  pull_request:
    branches:
      - "master"

jobs:
  unittest:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    container: python:3.12-alpine

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        id: checkout
        uses: "actions/checkout@v4"
        with:
          repository: ${{ github.repository }}
      - name: "Run Unit Tests"
        run: python -m unittest discover
