name: "unittest"

on:
  pull_request:
    branches:
      - "master"

jobs:
  unittest:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    container: python:3.12-alpine

    env:
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_HALLOWEEN_ID }}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        id: checkout
        uses: "actions/checkout@v4"
        with:
          repository: ${{ github.repository }}
      - name: "Install Dependencies"
        run: pip install -r requirements.txt
      - name: "Generate Credentials JSON File"
        run: echo '${{ secrets.GOOGLE_CLOUD_SVC_CREDS }}' >> credentials.json
      - name: "Run Unit Tests"
        run: python -m unittest discover -v
